todo/urls.py
from django.contrib import admin
from django.urls import path

from todo.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    complete_or_undo,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("<int:pk>/complete_or_undo/", complete_or_undo, name="complete-or-undo"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),

]

app_name = "todo"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
]

todo/models.py
from django.db import models


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", blank=True)

    class Meta:
        ordering = ["done", "datetime"]

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

todo/forms.py
import datetime

from django import forms
from django.forms import DateTimeInput

from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    deadline = forms.DateTimeField(
        widget=DateTimeInput(attrs={'type': 'datetime-local'}),
        required=False
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    def clean_deadline(self):
        deadline = self.cleaned_data["deadline"]

        if deadline and deadline < datetime.datetime.today():
            raise forms.ValidationError("Deadline must be in the future!")
        return deadline

    class Meta:
        model = Task
        fields = ["content", "deadline", "tags"]

todo/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskForm
from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.all().prefetch_related("tags")


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")
    template_name = "todo/task_form.html"


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")
    template_name = "todo/task_form.html"


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")
    template_name = "todo/task_confirm_delete.html"


def complete_or_undo(request, pk):
    task = Task.objects.get(pk=pk)
    task.done = not task.done
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo:task-list"))


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")
    template_name = "todo/tag_form.html"


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")
    template_name = "todo/tag_form.html"


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")
    template_name = "todo/tag_confirm_delete.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>
</html>

templates/includes/create_or_update_form.html
{% load crispy_forms_filters %}
<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="{{ object|yesno:'Update,Create' }}">
</form>

templates/includes/sidebar.html
<div class="list-group" id="list-tab" role="tablist">
    <a class="list-group-item list-group-item-action" id="list-home-list" data-toggle="list"
       href="{% url 'todo:task-list' %}" role="tab" aria-controls="home">Home</a>
    <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list"
       href="{% url 'todo:tag-list' %}" role="tab" aria-controls="profile">Tags</a>
</div>

templates/todo/tag_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <p>Are you sure you want to delete tag: {{ tag.name }}?</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, I'm sure" class="btn btn-secondary">
    </form>
{% endblock %}

templates/todo/tag_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ object|yesno:'Update,Create' }} tag</h1>
    {% include "includes/create_or_update_form.html" %}
{% endblock %}

templates/todo/tag_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>
        Tags
        <a href="{% url 'todo:tag-create' %}" class="badge badge-pill badge-secondary float-right">Add tag</a>
    </h1>
    {% if tag_list %}
        {% for tag in tag_list %}
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ tag.name }}</h5>
                    <a href="{% url 'todo:tag-update' pk=tag.id %}" class="badge badge-primary">Update</a>
                    <a href="{% url 'todo:tag-delete' pk=tag.id %}" class="badge badge-danger">Delete</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No tags found.</p>
    {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <p>Are you sure you want to delete task: {{ task.content }}?</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, I'm sure" class="btn btn-secondary">
    </form>
{% endblock %}

templates/todo/task_form.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ object|yesno:'Update,Create' }} task</h1>
    {% include "includes/create_or_update_form.html" %}
{% endblock %}

templates/todo/task_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>
        TODO list
        <a href="{% url 'todo:task-create' %}" class="badge badge-pill badge-secondary float-right">Add task</a>
    </h1>

    {% if task_list %}
        <ul class="list-group list-group-flush">
            {% for task in task_list %}

                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-9">
                            <ul class="list-unstyled">
                                <li>
                                    <h5>
                                        {{ task.content }}
                                        {% if task.done %}
                                            <span class="badge badge-pill badge-success">Done</span>
                                        {% else %}
                                            <span class="badge badge-pill badge-danger">Not done</span>
                                        {% endif %}
                                    </h5>
                                </li>
                                <li><small>Created: {{ task.datetime }}</small></li>
                            {% if task.deadline %}
                                <li><small>Deadline: {{ task.deadline }}</small></li>
                            {% endif %}
                                <li>
                                    <p class="text-muted">Tags:
                                        {% for tag in task.tags.all %}
                                            <span class="badge badge-pill badge-secondary">{{ tag.name }}</span>
                                        {% endfor %}
                                    </p>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-1">

                            <a href="{% url 'todo:complete-or-undo' pk=task.id %}"
                               class="badge badge-pill {% if task.done %}badge-secondary">Undo{% else %}
                                   badge-success">Complete{% endif %}</a><br>
                            <a href="{% url 'todo:task-update' pk=task.id %}"
                               class="badge badge-pill badge-primary">Edit</a><br>
                            <a href="{% url 'todo:task-delete' pk=task.id %}" class="badge badge-pill badge-danger">Delete</a>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No tasks yet</p>

    {% endif %}

{% endblock %}